# Generated by Django 5.0.6 on 2026-01-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.examquestion')),
                ('selected_alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.alternative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
