# Generated by Django 5.0.6 on 2026-01-10 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='examanswer',
            constraint=models.UniqueConstraint(fields=('student', 'exam_question'), name='unique_student_exam_question'),
        ),
    ]
